# Generated by Django 4.0.6 on 2022-08-19 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wb_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmId', models.IntegerField(unique=True)),
                ('price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('promocode', models.IntegerField(default=0)),
                ('org', models.IntegerField(default=0)),
                ('dataparsing', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
