# Generated by Django 4.0.6 on 2022-08-25 04:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0002_wb_products_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(default='', max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('retail_price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('retail_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('barcode', models.CharField(default='', max_length=200)),
                ('sale_dt', models.DateField(default=django.utils.timezone.now)),
                ('subject_name', models.CharField(default='', max_length=200)),
                ('brand_name', models.CharField(default='', max_length=200)),
                ('org', models.IntegerField(default=0)),
                ('nm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb.wb_info')),
            ],
        ),
    ]
