# Generated by Django 4.0.6 on 2022-08-26 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0003_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(default='', max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('warehouse', models.IntegerField(default=0)),
                ('warehouseName', models.CharField(default='', max_length=200)),
                ('nmId', models.CharField(default='', max_length=200)),
                ('brand', models.CharField(default='', max_length=200)),
                ('subject', models.CharField(default='', max_length=200)),
                ('Price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('Discount', models.IntegerField(default=0)),
                ('dataparsing', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
