# Generated by Django 4.0.6 on 2022-08-29 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0004_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('lastChangeDate', models.DateField(default=django.utils.timezone.now)),
                ('supplierArticle', models.CharField(default='', max_length=200)),
                ('barcode', models.CharField(default='', max_length=200)),
                ('totalPrice', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('discountPercent', models.IntegerField(default=0)),
                ('warehouseName', models.IntegerField(default=0)),
                ('forPay', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('finishedPrice', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('priceWithDisc', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('nmId', models.IntegerField(default=0)),
            ],
        ),
    ]
