# Generated by Django 4.0.6 on 2022-08-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0006_sales_saleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='warehouseName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
