# Generated by Django 4.0.6 on 2022-08-16 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ecom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('ref', models.CharField(max_length=36, unique=True)),
                ('delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=36, unique=True)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='nomenklature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articul', models.CharField(max_length=100)),
                ('shtrih', models.CharField(max_length=300)),
                ('ref', models.CharField(max_length=36)),
                ('parentref', models.CharField(max_length=36)),
                ('lider', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('partref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ecom')),
            ],
        ),
    ]
