# Generated by Django 4.0.6 on 2022-09-07 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='linkparser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataparsing', models.DateField(default=django.utils.timezone.now)),
                ('pos', models.IntegerField(default=0)),
                ('region', models.CharField(max_length=250)),
                ('link', models.TextField(default='')),
                ('lower_price', models.CharField(default='', max_length=50)),
                ('old_price', models.CharField(default='', max_length=50)),
                ('brand_name', models.CharField(default='', max_length=100)),
                ('goods_name', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
