# Generated by Django 4.0.6 on 2022-09-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_keywords_linkparser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkparser',
            name='brand_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='linkparser',
            name='goods_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
