# Generated by Django 4.0.6 on 2022-09-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_linkparser_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkparser',
            name='ecom',
            field=models.IntegerField(default=0),
        ),
    ]
