# Generated by Django 4.0.6 on 2022-10-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foto_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(default='', max_length=50)),
                ('link', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
