# Generated by Django 4.0.6 on 2022-08-17 10:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='metrics_ozon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.IntegerField(default=0)),
                ('dataparsing', models.DateField(default=django.utils.timezone.now)),
                ('hits_view', models.IntegerField(default=0)),
                ('hits_tocart', models.IntegerField(default=0)),
                ('revenue', models.IntegerField(default=0)),
                ('returns', models.IntegerField(default=0)),
                ('ordered_units', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ozon.prod_ozon')),
            ],
        ),
    ]
