# Generated by Django 4.0.6 on 2022-08-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0003_metrics_ozon_cancellations'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics_ozon',
            name='conv_tocart_pdp',
            field=models.IntegerField(default=0),
        ),
    ]
