# Generated by Django 4.0.6 on 2022-08-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0004_metrics_ozon_conv_tocart_pdp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metrics_ozon',
            old_name='conv_tocart_pdp',
            new_name='conv_tocart',
        ),
    ]
