# Generated by Django 4.0.6 on 2022-08-18 05:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0005_rename_conv_tocart_pdp_metrics_ozon_conv_tocart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ozon_stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataparsing', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(max_length=50)),
                ('present', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ozon.prod_ozon')),
            ],
        ),
    ]
