# Generated by Django 4.0.6 on 2022-08-29 13:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0006_ozon_stocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ozon_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataparsing', models.DateField(default=django.utils.timezone.now)),
                ('price', models.IntegerField(default=0)),
                ('old_price', models.IntegerField(default=0)),
                ('vat', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ozon.prod_ozon')),
            ],
        ),
    ]
