# Generated by Django 4.0.6 on 2022-08-30 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0007_ozon_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ozon_stock_warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataparsing', models.DateField(default=django.utils.timezone.now)),
                ('sku', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=250)),
                ('brand', models.CharField(default='', max_length=200)),
                ('present', models.IntegerField(default=0)),
            ],
        ),
    ]
