# Generated by Django 4.0.6 on 2022-08-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0008_ozon_stock_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='ozon_stock_warehouse',
            name='warehouse',
            field=models.CharField(default='', max_length=250),
        ),
    ]
