# Generated by Django 4.0.6 on 2022-08-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0009_ozon_stock_warehouse_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ozon_stock_warehouse',
            name='present',
            field=models.CharField(default='', max_length=50),
        ),
    ]
