# Generated by Django 4.0.6 on 2022-08-30 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sale', models.DateField(default=django.utils.timezone.now)),
                ('idBrand', models.CharField(default='', max_length=50)),
                ('brand', models.CharField(default='', max_length=200)),
                ('sku', models.CharField(default='', max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('hits_view', models.IntegerField(default=0)),
                ('hits_tocart', models.IntegerField(default=0)),
                ('ordered_units', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
            ],
        ),
    ]
