# Generated by Django 4.0.6 on 2022-08-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='revenue',
            field=models.IntegerField(default=0),
        ),
    ]
