# Generated by Django 4.0.6 on 2022-08-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex', '0003_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='units',
            field=models.IntegerField(default=0),
        ),
    ]
