# Generated by Django 4.0.6 on 2022-09-19 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yandex', '0007_rec_adwords'),
    ]

    operations = [
        migrations.CreateModel(
            name='metrics_site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataparsing', models.DateField(default=django.utils.timezone.now)),
                ('regionCountry', models.CharField(default='', max_length=250)),
                ('regionArea', models.CharField(default='', max_length=250)),
                ('visits', models.IntegerField(default=0)),
                ('users', models.IntegerField(default=0)),
                ('pageviews', models.IntegerField(default=0)),
            ],
        ),
    ]
